### ISSUE TITLE
KSgeneral has been removed from CRAN

### ISSUE THREAD

**Issue by florisvdh** [raymondtsr/ksgeneral#4]
See https://CRAN.R-project.org/package=KSgeneral. Is the intention to keep the package maintained on CRAN?

I made a package that has `KSgeneral` [as a dependency](https://github.com/inbo/watina/blob/e85059822903ce2638e5408e984a2476cb02ff6b/DESCRIPTION#L26); the package currently won't install unless taking `KSgeneral` from GitHub instead of CRAN.

**Comment by prestevez** [comment]
Any update on this issue?

**Comment by florisvdh** [comment]
`KSgeneral` is back on CRAN. Thanks for solving!
